REMOVE := \
	.chatgpt-shell.el \
	.emacs.desktop \
	.org-id-locations \
	auto-save-list \
	bookmarks \
	chatgpt \
	custom.el \
	eln-cache \
	elpa \
	org-roam.db \
	projects \
	recentf \
	tramp \
	transient \
	url \
	eshell

.PHONY: clean

clean:
	rm -rf $(REMOVE)
